-- Run-specific, credential-free verification. Use the isolated test warehouse.
CREATE VIEW EVSNOW_ELASTIC_261005_1931.PUBLIC.EVENTS_BY_EVENT_ID AS
SELECT * FROM EVSNOW_ELASTIC_261005_1931.PUBLIC.EVENTS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRY_PARSE_JSON(EVENT_BODY):run_id::VARCHAR,
                 TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER
    ORDER BY INGESTION_TIMESTAMP DESC, EVENT_BODY
) = 1;

SELECT COUNT(*) RAW_ROWS,
       COUNT(DISTINCT TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) DISTINCT_IDS,
       COUNT(*)-COUNT(DISTINCT TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) DUPLICATE_ROWS
FROM EVSNOW_ELASTIC_261005_1931.PUBLIC.EVENTS;

SELECT COUNT(*) DEDUPLICATED_ROWS,
       COUNT(DISTINCT TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) DISTINCT_IDS,
       MIN(TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) FIRST_ID,
       MAX(TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) LAST_ID,
       COALESCE(COUNT_IF(
           TRY_PARSE_JSON(EVENT_BODY):value::NUMBER <>
           TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER*17+3
       ),0) INVALID_VALUES
FROM EVSNOW_ELASTIC_261005_1931.PUBLIC.EVENTS_BY_EVENT_ID;

SELECT COUNT(*) PROCESSING_ERRORS
FROM ERROR_TABLE(EVSNOW_ELASTIC_261005_1931.PUBLIC.EVENTS);

SELECT PARTITION_ID, WATERLEVEL,
       METADATA:sequence_number::NUMBER SAVED_SEQUENCE,
       METADATA:offset_string::VARCHAR SAVED_OFFSET
FROM EVSNOW_ELASTIC_261005_1931.PUBLIC.INGESTION_STATUS
ORDER BY PARTITION_ID;
