USE ROLE ACCOUNTADMIN;
USE WAREHOUSE EVSNOW_ELASTIC_FIXES_261005_2043_WH;
ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS=60;
-- Run-specific, credential-free verification. Use the isolated test warehouse.
CREATE VIEW EVSNOW_ELASTIC_FIXES_261005_2043.PUBLIC.EVENTS_BY_EVENT_ID AS
SELECT * FROM EVSNOW_ELASTIC_FIXES_261005_2043.PUBLIC.EVENTS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRY_PARSE_JSON(EVENT_BODY):run_id::VARCHAR,
                 TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER
    ORDER BY INGESTION_TIMESTAMP DESC, EVENT_BODY
) = 1;

SELECT COUNT(*) RAW_ROWS,
       COUNT(DISTINCT TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) DISTINCT_IDS,
       COUNT(*)-COUNT(DISTINCT TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) DUPLICATE_ROWS
FROM EVSNOW_ELASTIC_FIXES_261005_2043.PUBLIC.EVENTS;

SELECT COUNT(*) DEDUPLICATED_ROWS,
       COUNT(DISTINCT TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) DISTINCT_IDS,
       MIN(TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) FIRST_ID,
       MAX(TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER) LAST_ID,
       COALESCE(COUNT_IF(
           TRY_PARSE_JSON(EVENT_BODY):value::NUMBER <>
           TRY_PARSE_JSON(EVENT_BODY):event_id::NUMBER*17+3
       ),0) INVALID_VALUES
FROM EVSNOW_ELASTIC_FIXES_261005_2043.PUBLIC.EVENTS_BY_EVENT_ID;

SELECT COUNT(*) PROCESSING_ERRORS
FROM ERROR_TABLE(EVSNOW_ELASTIC_FIXES_261005_2043.PUBLIC.EVENTS);

SELECT PARTITION_ID, WATERLEVEL,
       METADATA:sequence_number::NUMBER SAVED_SEQUENCE,
       METADATA:offset_string::VARCHAR SAVED_OFFSET
FROM EVSNOW_ELASTIC_FIXES_261005_2043.PUBLIC.INGESTION_STATUS
ORDER BY PARTITION_ID;

WITH events AS (
    SELECT TRY_PARSE_JSON(EVENT_BODY) BODY, EVENTHUB_NAMESPACE, EVENTHUB_NAME,
           PARTITION_ID, SEQUENCE_NUMBER FROM EVSNOW_ELASTIC_FIXES_261005_2043.PUBLIC.EVENTS_BY_EVENT_ID
), ids AS (
    SELECT *, TRY_TO_NUMBER(BODY:event_id::VARCHAR) ID FROM events
)
SELECT COUNT(*) DEDUPLICATED_ROWS, COUNT(DISTINCT ID) DISTINCT_IDS,
       MIN(ID) FIRST_ID, MAX(ID) LAST_ID,
       COALESCE(COUNT_IF(ID IS NULL OR ID<0 OR ID>=200000),0) INVALID_IDS,
       COALESCE(COUNT_IF(BODY:run_id::VARCHAR IS NULL OR BODY:run_id::VARCHAR<>'elastic-fixes-20261005-2043'
         OR TRY_TO_NUMBER(BODY:value::VARCHAR) IS NULL OR TRY_TO_NUMBER(BODY:value::VARCHAR)<>ID*17+3
         OR BODY:message::VARCHAR IS NULL OR BODY:message::VARCHAR<>'elastic-'||LPAD(ID::VARCHAR,6,'0')),0) INVALID_PAYLOADS,
       COALESCE(COUNT_IF(EVENTHUB_NAMESPACE IS NULL OR EVENTHUB_NAMESPACE<>'evsnow-elastic-fixes-20261005-2043.servicebus.windows.net'
         OR EVENTHUB_NAME IS NULL OR EVENTHUB_NAME<>'events'
         OR PARTITION_ID IS NULL OR PARTITION_ID<>MOD(ID,2)::VARCHAR
         OR SEQUENCE_NUMBER IS NULL OR SEQUENCE_NUMBER<>FLOOR(ID/2)),0) INVALID_SOURCE_METADATA
FROM ids;
